name: Build Flutter Debug APK (pin Flutter)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools & accept licenses
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # 👇 Pinna Flutter a una versione stabile PRE-3.35 (compatibile con Kotlin vecchio)
      - name: Set up Flutter (3.24.4)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Flutter clean & pub get
        run: |
          flutter clean
          flutter pub get
          flutter precache --android

      - name: Build Debug APK
        run: flutter build apk --debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
