name: Build Flutter Debug APK (cached)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    env:
      JAVA_DISTRIBUTION: temurin
      JAVA_VERSION: '17'
      ANDROID_BUILD_TOOLS: '34.0.0'
      ANDROID_PLATFORM: 'android-34'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools & accept licenses
        run: |
          sdkmanager --install "platform-tools" "platforms;${{ env.ANDROID_PLATFORM }}" "build-tools;${{ env.ANDROID_BUILD_TOOLS }}"
          yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Flutter pub get
        run: flutter pub get

      - name: Precache Android
        run: flutter precache --android

      - name: Build Debug APK
        run: flutter build apk --debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
