name: atlas_ai_trader
description: "Atlas AI Trader - Intelligent Market Assistant for real-time trading signals."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.0
  intl: ^0.19.0
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.65.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.6.0
  shared_preferences: ^2.2.0
  markdown: ^7.1.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

